[2023-07-27T15:07:54.105+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_load.sql_extract __airflow_temporary_run_2023-07-27T15:07:48.088645+00:00__ [queued]>
[2023-07-27T15:07:54.231+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_load.sql_extract __airflow_temporary_run_2023-07-27T15:07:48.088645+00:00__ [queued]>
[2023-07-27T15:07:54.234+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-27T15:07:54.436+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): sql_extract> on 2023-07-26 00:00:00+00:00
[2023-07-27T15:07:54.523+0000] {standard_task_runner.py:57} INFO - Started process 6958 to run task
[2023-07-27T15:07:54.672+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'extract_and_load', 'sql_extract', '__***_temporary_run_2023-07-27T15:07:48.088645+00:00__', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpsfe3zhze']
[2023-07-27T15:07:54.886+0000] {standard_task_runner.py:85} INFO - Job 48: Subtask sql_extract
[2023-07-27T15:07:55.242+0000] {task_command.py:410} INFO - Running <TaskInstance: extract_and_load.sql_extract __airflow_temporary_run_2023-07-27T15:07:48.088645+00:00__ [running]> on host 54db880c2dec
[2023-07-27T15:07:56.258+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_load' AIRFLOW_CTX_TASK_ID='sql_extract' AIRFLOW_CTX_EXECUTION_DATE='2023-07-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='__***_temporary_run_2023-07-27T15:07:48.088645+00:00__'
[2023-07-27T15:07:56.345+0000] {base.py:73} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2023-07-27T15:07:56.562+0000] {sql.py:375} INFO - Running statement:  SELECT table_name
                      FROM information_schema.tables
                      WHERE table_schema = 'employees' AND table_name = 'employees' , parameters: None
[2023-07-27T15:07:56.563+0000] {sql.py:384} INFO - Rows affected: 1
[2023-07-27T15:07:56.631+0000] {logging_mixin.py:150} INFO - (('employees',),)
[2023-07-27T15:07:56.632+0000] {python.py:183} INFO - Done. Returned value was: ('employees',)
[2023-07-27T15:07:56.706+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2361, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 214, in set
    raise ValueError(f"DAG run not found on DAG {dag_id!r} with ID {run_id!r}")
ValueError: DAG run not found on DAG 'extract_and_load' with ID '__***_temporary_run_2023-07-27T15:07:48.088645+00:00__'
[2023-07-27T15:07:56.904+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=extract_and_load, task_id=sql_extract, execution_date=20230726T000000, start_date=20230727T150754, end_date=20230727T150756
[2023-07-27T15:07:57.088+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 48 for task sql_extract ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(extract_and_load, sql_extract, __airflow_temporary_run_2023-07-27T15:07:48.088645+00:00__, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'sql_extract', 'dag_id': 'extract_and_load', 'run_id': '__airflow_temporary_run_2023-07-27T15:07:48.088645+00:00__', 'map_index': -1, 'start_date': datetime.datetime(2023, 7, 27, 15, 7, 54, 124113, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2023, 7, 27, 15, 7, 56, 902071, tzinfo=Timezone('UTC')), 'duration': 2}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 6958)
[2023-07-27T15:07:57.245+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
