[2023-07-29T08:24:38.170+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_copy.dbt_run manual__2023-07-29T08:23:01.806175+00:00 [queued]>
[2023-07-29T08:24:38.239+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_copy.dbt_run manual__2023-07-29T08:23:01.806175+00:00 [queued]>
[2023-07-29T08:24:38.248+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-29T08:24:38.433+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): dbt_run> on 2023-07-29 08:23:01.806175+00:00
[2023-07-29T08:24:38.443+0000] {standard_task_runner.py:57} INFO - Started process 633 to run task
[2023-07-29T08:24:38.466+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'full_copy', 'dbt_run', 'manual__2023-07-29T08:23:01.806175+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/full_copy.py', '--cfg-path', '/tmp/tmpoq6kd8ki']
[2023-07-29T08:24:38.473+0000] {standard_task_runner.py:85} INFO - Job 277: Subtask dbt_run
[2023-07-29T08:24:38.632+0000] {task_command.py:410} INFO - Running <TaskInstance: full_copy.dbt_run manual__2023-07-29T08:23:01.806175+00:00 [running]> on host e6ac5424eb0d
[2023-07-29T08:24:38.945+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_copy' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2023-07-29T08:23:01.806175+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-29T08:23:01.806175+00:00'
[2023-07-29T08:24:38.989+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-29T08:24:38.990+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'source /opt/***/dags/dbt/dbt/Scripts/activate && dbt run --models .']
[2023-07-29T08:24:39.105+0000] {subprocess.py:86} INFO - Output:
[2023-07-29T08:24:39.125+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-07-29T08:24:39.127+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-07-29T08:24:39.171+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-29T08:24:39.183+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=full_copy, task_id=dbt_run, execution_date=20230729T082301, start_date=20230729T082438, end_date=20230729T082439
[2023-07-29T08:24:39.251+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 277 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 633)
[2023-07-29T08:24:39.304+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-29T08:24:39.385+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
