[2023-07-29T08:23:32.246+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_copy.dbt_run manual__2023-07-29T08:23:01.806175+00:00 [queued]>
[2023-07-29T08:23:32.265+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_copy.dbt_run manual__2023-07-29T08:23:01.806175+00:00 [queued]>
[2023-07-29T08:23:32.266+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-07-29T08:23:32.371+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): dbt_run> on 2023-07-29 08:23:01.806175+00:00
[2023-07-29T08:23:32.381+0000] {standard_task_runner.py:57} INFO - Started process 593 to run task
[2023-07-29T08:23:32.402+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'full_copy', 'dbt_run', 'manual__2023-07-29T08:23:01.806175+00:00', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/full_copy.py', '--cfg-path', '/tmp/tmpdvrhdxbe']
[2023-07-29T08:23:32.412+0000] {standard_task_runner.py:85} INFO - Job 276: Subtask dbt_run
[2023-07-29T08:23:32.596+0000] {task_command.py:410} INFO - Running <TaskInstance: full_copy.dbt_run manual__2023-07-29T08:23:01.806175+00:00 [running]> on host e6ac5424eb0d
[2023-07-29T08:23:33.029+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_copy' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2023-07-29T08:23:01.806175+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-29T08:23:01.806175+00:00'
[2023-07-29T08:23:33.035+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-29T08:23:33.036+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'source /opt/***/dags/dbt/dbt/Scripts/activate && dbt run --models .']
[2023-07-29T08:23:33.072+0000] {subprocess.py:86} INFO - Output:
[2023-07-29T08:23:33.090+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-07-29T08:23:33.091+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-07-29T08:23:33.123+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-07-29T08:23:33.155+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=full_copy, task_id=dbt_run, execution_date=20230729T082301, start_date=20230729T082332, end_date=20230729T082333
[2023-07-29T08:23:33.203+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 276 for task dbt_run (Bash command failed. The command returned a non-zero exit code 127.; 593)
[2023-07-29T08:23:33.257+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-29T08:23:33.292+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
