[2023-07-29T08:21:33.135+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_copy.dbt_run manual__2023-07-29T08:19:49.144632+00:00 [queued]>
[2023-07-29T08:21:33.155+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_copy.dbt_run manual__2023-07-29T08:19:49.144632+00:00 [queued]>
[2023-07-29T08:21:33.156+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-29T08:21:33.194+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): dbt_run> on 2023-07-29 08:19:49.144632+00:00
[2023-07-29T08:21:33.203+0000] {standard_task_runner.py:57} INFO - Started process 520 to run task
[2023-07-29T08:21:33.215+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'full_copy', 'dbt_run', 'manual__2023-07-29T08:19:49.144632+00:00', '--job-id', '273', '--raw', '--subdir', 'DAGS_FOLDER/full_copy.py', '--cfg-path', '/tmp/tmpf25m9y3p']
[2023-07-29T08:21:33.221+0000] {standard_task_runner.py:85} INFO - Job 273: Subtask dbt_run
[2023-07-29T08:21:33.398+0000] {task_command.py:410} INFO - Running <TaskInstance: full_copy.dbt_run manual__2023-07-29T08:19:49.144632+00:00 [running]> on host e6ac5424eb0d
[2023-07-29T08:21:33.672+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_copy' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2023-07-29T08:19:49.144632+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-29T08:19:49.144632+00:00'
[2023-07-29T08:21:33.679+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-29T08:21:33.680+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'source /opt/***/dags/dbt/dbt/Scripts/ && dbt run --models .']
[2023-07-29T08:21:33.707+0000] {subprocess.py:86} INFO - Output:
[2023-07-29T08:21:33.714+0000] {subprocess.py:93} INFO - /bin/bash: line 1: source: /opt/***/dags/dbt/dbt/Scripts/: is a directory
[2023-07-29T08:21:33.716+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-07-29T08:21:33.747+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-07-29T08:21:33.755+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=full_copy, task_id=dbt_run, execution_date=20230729T081949, start_date=20230729T082133, end_date=20230729T082133
[2023-07-29T08:21:33.804+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 273 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 520)
[2023-07-29T08:21:33.844+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-29T08:21:33.898+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
